export { default as Hero } from "./Hero"
export { default as Sales } from "./Sales"
export { default as FlexContent } from "./FlexContent"
export { default as Stories } from "./Stories"
export { default as Footer } from "./Footer"
export { default as Navbar } from "./Navbar"
export { default as Cart } from "./Cart"